# Generated by Django 5.0.3 on 2024-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(default="null", upload_to="club_images/"),
            preserve_default=False,
        ),
    ]
