# Generated by Django 5.0.3 on 2024-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="image",
            field=models.ImageField(upload_to="static/club_images/"),
        ),
    ]
